# Generated by Django 4.2.7 on 2023-11-25 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='Электронная почта')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('surame', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('fathers_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчество')),
                ('comment', models.TextField(verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Последняя попытка')),
                ('status', models.CharField(max_length=50, verbose_name='Статус попытки')),
                ('response', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ответ почтового сервера')),
            ],
            options={
                'verbose_name': 'Лог',
                'verbose_name_plural': 'Логи',
            },
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailing_time', models.TimeField(verbose_name='Время рассылки')),
                ('mailing_period', models.CharField(max_length=50, verbose_name='Период рассылки')),
                ('mailing_status', models.CharField(max_length=50, verbose_name='Статус рассылки')),
                ('mail_header', models.CharField(max_length=150, verbose_name='Тема письма')),
                ('mail_message', models.TextField(verbose_name='Текст письма')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
            },
        ),
    ]
