# Generated by Django 4.2.7 on 2023-11-27 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0003_rename_recepients_mailing_recepient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='mailing_period',
            field=models.CharField(choices=[('PD', 'Раз в сутки'), ('PW', 'Раз в неделю'), ('PM', 'Раз в месяц')], max_length=50, verbose_name='Период рассылки'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='recepient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='service_app.clients', verbose_name='Адресант'),
        ),
    ]
