# Generated by Django 4.2.7 on 2023-11-27 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0004_alter_mailing_mailing_period_alter_mailing_recepient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='mailing_status',
            field=models.CharField(choices=[('CNL', 'Не активна'), ('ACT', 'Активна')], max_length=50, verbose_name='Статус рассылки'),
        ),
    ]
