# Generated by Django 4.2.7 on 2023-11-30 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0006_remove_mailing_recepient_mailing_recepient'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='mailing_day',
            field=models.CharField(choices=[('MON', 'Понедельник'), ('TUE', 'Вторник'), ('WEN', 'Среда'), ('THO', 'Четверг'), ('FRI', 'Пятница'), ('SAT', 'Суббота'), ('SUN', 'Воскресенье')], default='MON', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='recepient',
            field=models.ManyToManyField(blank=True, related_name='recepirnts', to='service_app.clients', verbose_name='Адресант'),
        ),
    ]
