# Generated by Django 4.2.7 on 2023-11-30 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0007_mailing_mailing_day_alter_mailing_recepient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='mailing_day',
            field=models.CharField(choices=[('MON', 'Понедельник'), ('TUE', 'Вторник'), ('WEN', 'Среда'), ('THO', 'Четверг'), ('FRI', 'Пятница'), ('SAT', 'Суббота'), ('SUN', 'Воскресенье')], default=('MON', 'Понедельник'), verbose_name=''),
        ),
    ]
