# Generated by Django 4.2.7 on 2023-12-01 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0009_alter_mailing_mail_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='mailing_day_of_month',
            field=models.IntegerField(blank=True, null=True, verbose_name='День в месяце'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='mailing_day',
            field=models.CharField(choices=[('mon', 'Понедельник'), ('tue', 'Вторник'), ('wed', 'Среда'), ('thu', 'Четверг'), ('fri', 'Пятница'), ('sat', 'Суббота'), ('sun', 'Воскресенье')], default=('MON', 'Понедельник'), verbose_name=''),
        ),
    ]
