# Generated by Django 4.2.7 on 2023-12-02 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0010_mailing_mailing_day_of_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='mailing_day',
            field=models.CharField(choices=[('mon', 'Понедельник'), ('tue', 'Вторник'), ('wed', 'Среда'), ('thu', 'Четверг'), ('fri', 'Пятница'), ('sat', 'Суббота'), ('sun', 'Воскресенье')], verbose_name='День рассылки'),
        ),
    ]
