# Generated by Django 4.2.7 on 2023-12-11 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0013_logs_email_logs_mail_header_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='')),
                ('permissions', models.CharField(choices=[('ADMIN', 'Админ'), ('USR', 'Пользователь'), ('BND', 'Забанен'), ('GST', 'Гость')], default=('USR', 'Пользователь'))),
                ('clients', models.ManyToManyField(blank=True, null=True, to='service_app.clients', verbose_name='')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
