# Generated by Django 4.2.7 on 2023-12-11 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0014_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
