# Generated by Django 4.2.7 on 2023-12-30 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0015_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='client_author',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='logs',
            name='log_author',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='mailing_author',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Автор'),
        ),
    ]
